=== JujaLabs/itevents/restservice/src/test/resources/dbunit/test.dtd
<!ELEMENT dataset (
    city*,
    crawler*,
    currency*,
    databasechangelog*,
    databasechangeloglock*,
    event*,
    event_technology*,
    filter*,
    filter_technology*,
    one_time_password*,
    role*,
    spatial_ref_sys*,
    technology*,
    user_event*,
    user_filter*,
    user_profile*,
    visit_log*)>

    <!ELEMENT city EMPTY>
    <!ATTLIST city
        id CDATA #IMPLIED
        name CDATA #REQUIRED
        details CDATA #IMPLIED
        point CDATA #REQUIRED
        >

    <!ELEMENT crawler EMPTY>
    <!ATTLIST crawler
        id CDATA #IMPLIED
        integration_name CDATA #REQUIRED
        integration_event_url CDATA #REQUIRED
        event_id CDATA #IMPLIED
        >

    <!ELEMENT currency EMPTY>
    <!ATTLIST currency
        id CDATA #IMPLIED
        name CDATA #REQUIRED
        >

    <!ELEMENT databasechangelog EMPTY>
    <!ATTLIST databasechangelog
        id CDATA #REQUIRED
        author CDATA #REQUIRED
        filename CDATA #REQUIRED
        dateexecuted CDATA #REQUIRED
        orderexecuted CDATA #REQUIRED
        exectype CDATA #REQUIRED
        md5sum CDATA #IMPLIED
        description CDATA #IMPLIED
        comments CDATA #IMPLIED
        tag CDATA #IMPLIED
        liquibase CDATA #IMPLIED
        contexts CDATA #IMPLIED
        labels CDATA #IMPLIED
        >

    <!ELEMENT databasechangeloglock EMPTY>
    <!ATTLIST databasechangeloglock
        id CDATA #REQUIRED
        locked CDATA #REQUIRED
        lockgranted CDATA #IMPLIED
        lockedby CDATA #IMPLIED
        >

    <!ELEMENT event EMPTY>
    <!ATTLIST event
        id CDATA #IMPLIED
        title CDATA #REQUIRED
        event_date CDATA #REQUIRED
        create_date CDATA #IMPLIED
        reg_link CDATA #IMPLIED
        address CDATA #IMPLIED
        point CDATA #IMPLIED
        contact CDATA #IMPLIED
        price CDATA #IMPLIED
        currency_id CDATA #IMPLIED
        city_id CDATA #IMPLIED
        description CDATA #IMPLIED
        >

    <!ELEMENT event_technology EMPTY>
    <!ATTLIST event_technology
        event_id CDATA #REQUIRED
        technology_id CDATA #REQUIRED
        >

    <!ELEMENT filter EMPTY>
    <!ATTLIST filter
        id CDATA #IMPLIED
        row_limit CDATA #IMPLIED
        create_date CDATA #REQUIRED
        city_id CDATA #IMPLIED
        free CDATA #IMPLIED
        longitude CDATA #IMPLIED
        latitude CDATA #IMPLIED
        radius CDATA #IMPLIED
        >

    <!ELEMENT filter_technology EMPTY>
    <!ATTLIST filter_technology
        filter_id CDATA #REQUIRED
        technology_id CDATA #REQUIRED
        >

    <!ELEMENT one_time_password EMPTY>
    <!ATTLIST one_time_password
        user_id CDATA #IMPLIED
        password CDATA #REQUIRED
        expiration_date CDATA #IMPLIED
        >

    <!ELEMENT role EMPTY>
    <!ATTLIST role
        id CDATA #IMPLIED
        name CDATA #IMPLIED
        >

    <!ELEMENT spatial_ref_sys EMPTY>
    <!ATTLIST spatial_ref_sys
        srid CDATA #REQUIRED
        auth_name CDATA #IMPLIED
        auth_srid CDATA #IMPLIED
        srtext CDATA #IMPLIED
        proj4text CDATA #IMPLIED
        >

    <!ELEMENT technology EMPTY>
    <!ATTLIST technology
        id CDATA #IMPLIED
        name CDATA #REQUIRED
        >

    <!ELEMENT user_event EMPTY>
    <!ATTLIST user_event
        user_id CDATA #REQUIRED
        event_id CDATA #REQUIRED
        created_date CDATA #IMPLIED
        deleted_date CDATA #IMPLIED
        deleted_reason CDATA #IMPLIED
        id CDATA #IMPLIED
        >

    <!ELEMENT user_filter EMPTY>
    <!ATTLIST user_filter
        user_id CDATA #REQUIRED
        filter_id CDATA #REQUIRED
        >

    <!ELEMENT user_profile EMPTY>
    <!ATTLIST user_profile
        id CDATA #IMPLIED
        login CDATA #REQUIRED
        password CDATA #REQUIRED
        role_id CDATA #REQUIRED
        subscribed CDATA #IMPLIED
        >

    <!ELEMENT visit_log EMPTY>
    <!ATTLIST visit_log
        id CDATA #IMPLIED
        event_id CDATA #REQUIRED
        date CDATA #REQUIRED
        user_id CDATA #REQUIRED
        >

=== JujaLabs/itevents/restservice/src/test/resources/dbunit/TechnologyMapperTest/TechnologyMapperTest_initial.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/dbunit/test.dtd">
<dataset>
    <technology id="-10" name="SQL"/>
    <technology id="-9" name="MyBatis"/>
    <technology id="-8" name="Spring"/>
    <technology id="-7" name="Ant"/>
    <technology id="-6" name="Maven"/>
    <technology id="-5" name="Gradle"/>
    <technology id="-4" name="Liquibase"/>
    <technology id="-3" name="PHP"/>
    <technology id="-2" name="JavaScript"/>
    <technology id="-1" name="Java"/>
</dataset>

=== JujaLabs/itevents/crawler/src/test/resources/dbunit/integrationEventMapperTest/shouldGetIntegrationEventsByIntegrationName_initial.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--<!DOCTYPE dataset SYSTEM "src/test/resources/dbunit/test.dtd">-->
<dataset>
    <city id="-1" name="Kyiv" point="POINT(30.523 50.4505)"/>
    <event id="-1" title="Java" event_date="2115-07-10 00:00:00.0"
           reg_link="http://www.java.com.ua"
           address="Beresteyska"
           point="POINT(30.742017 50.458585)" contact="java@gmail.com"
           city_id="-1" description="Java event in Kyiv"/>
    <technology id="-1" name="Java"/>
    <technology id="-4" name="Liquibase"/>
    <technology id="-8" name="Spring"/>
    <technology id="-9" name="MyBatis"/>
    <event_technology event_id="-1" technology_id="-1"/>
    <event_technology event_id="-1" technology_id="-4"/>
    <event_technology event_id="-1" technology_id="-8"/>
    <event_technology event_id="-1" technology_id="-9"/>
    <crawler id="-1" integration_name="SampleIntegration"
             integration_event_url="www" event_id="-1"/>
</dataset>

=== JujaLabs/itevents/restservice/src/test/resources/dbunit/FilterMapperTest/FilterMapperTest_initial.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/dbunit/test.dtd">
<dataset>
    <city id="-4" name="Odessa" details="Odessa, Florida, USA" point="POINT(-82.568333 28.183333)"/>
    <city id="-3" name="Boyarka" point="POINT(30.28861 50.32917)"/>
    <city id="-2" name="Odessa" point="POINT(30.73333 46.46667)"/>
    <city id="-1" name="Kyiv" point="POINT(30.523 50.4505)"/>
    <filter id="-5" create_date="2015-07-14" city_id="-1" free="false"/>
    <filter id="-4" create_date="2015-07-13"/>
    <filter id="-3" create_date="2015-07-12" city_id="-1" free="false"/>
    <filter id="-2" create_date="2015-07-11" free="true"/>
    <filter id="-1" create_date="2015-07-10" city_id="-1"/>
    <role id="-3" name="subscriber"/>
    <role id="-2" name="admin"/>
    <role id="-1" name="guest"/>
    <user_profile id="-4" login="vlasov@email.com" password="alex" role_id="-3"/>
    <user_profile id="-3" login="kuchin@email.com" password="viktor" role_id="-2"/>
    <user_profile id="-2" login="anakin@email.com" password="alex" role_id="-2"/>
    <user_profile id="-1" login="guest" password="guest" role_id="-1"/>
    <user_filter user_id="-4" filter_id="-3"/>
    <user_filter user_id="-3" filter_id="-5"/>
    <user_filter user_id="-3" filter_id="-4"/>
    <user_filter user_id="-2" filter_id="-2"/>
    <user_filter user_id="-2" filter_id="-1"/>
    <technology id="-10" name="SQL"/>
    <technology id="-9" name="MyBatis"/>
    <technology id="-8" name="Spring"/>
    <technology id="-7" name="Ant"/>
    <technology id="-6" name="Maven"/>
    <technology id="-5" name="Gradle"/>
    <technology id="-4" name="Liquibase"/>
    <technology id="-3" name="PHP"/>
    <technology id="-2" name="JavaScript"/>
    <technology id="-1" name="Java"/>
    <filter_technology filter_id="-4" technology_id="-3"/>
    <filter_technology filter_id="-4" technology_id="-1"/>
    <filter_technology filter_id="-3" technology_id="-5"/>
    <filter_technology filter_id="-3" technology_id="-3"/>
    <filter_technology filter_id="-2" technology_id="-7"/>
    <filter_technology filter_id="-2" technology_id="-4"/>
    <filter_technology filter_id="-2" technology_id="-2"/>
    <filter_technology filter_id="-1" technology_id="-9"/>
    <filter_technology filter_id="-1" technology_id="-8"/>
    <filter_technology filter_id="-1" technology_id="-6"/>
    <filter_technology filter_id="-1" technology_id="-1"/>
</dataset>

=== JujaLabs/itevents/restservice/src/test/resources/dbunit/UserMapperTest/testUpdateUser_expected.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/dbunit/test.dtd">
<dataset>
    <role id="-3" name="subscriber"/>
    <role id="-2" name="admin"/>
    <role id="-1" name="guest"/>
    <user_profile id="-4" login="vlasov@email.com" password="alex" role_id="-3" subscribed="true"/>
    <user_profile id="-3" login="kuchin@email.com" password="viktor" role_id="-2"/>
    <user_profile id="-2" login="anakin@email.com" password="alex" role_id="-2"/>
    <user_profile id="-1" login="guest" password="guest" role_id="-1"/>
</dataset>

=== JujaLabs/itevents/restservice/src/test/resources/dbunit/TechnologyMapperTest/testGetTechnologiesByEventId_initial.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/dbunit/test.dtd">
<dataset>
    <city id="-4" name="Odessa" details="Odessa, Florida, USA" point="POINT(-82.568333 28.183333)"/>
    <city id="-3" name="Boyarka" point="POINT(30.28861 50.32917)"/>
    <city id="-2" name="Odessa" point="POINT(30.73333 46.46667)"/>
    <city id="-1" name="Kyiv" point="POINT(30.523 50.4505)"/>
    <currency id="-3" name="Euro"/>
    <currency id="-2" name="&#1043;&#1088;&#1080;&#1074;&#1085;&#1072;"/>
    <currency id="-1" name="USD"/>
    <event id="-7" title="Delphi" event_date="2115-07-05 00:00:00.0" reg_link="http://www.delphi.com.ua"
           address="Arsenalna" point="POINT(30.547603 50.442843)" contact="delphi@gmail.com" price="30" currency_id="-1"
           city_id="-1"/>
    <event id="-6" title="CSharp" event_date="2115-07-09 00:00:00.0" reg_link="http://www.c#.com.ua"
           address="Khreschatyk" point="POINT(30.52239 50.447694)" contact="csharp@gmail.com" price="20"
           currency_id="-3" city_id="-3"/>
    <event id="-5" title="ObjectiveC" event_date="2115-07-05 00:00:00.0" reg_link="http://www.objective-c.com.ua"
           address="Provectus" point="POINT(30.758417 46.472508)" contact="objectivec@gmail.com" price="20"
           currency_id="-3" city_id="-2"/>
    <event id="-4" title="CPlusPlus" event_date="2115-07-15 00:00:00.0" reg_link="http://www.cplusplus.com.ua"
           address="Impact Hub" point="POINT(30.747175 46.481782)" contact="cplusplus@gmail.com" price="20"
           currency_id="-3" city_id="-2"/>
    <event id="-3" title="JS" event_date="2115-07-30 00:00:00.0" reg_link="http://www.js.com.ua" address="Nyvky"
           point="POINT(30.403965 50.458651)" contact="js@gmail.com" price="20" currency_id="-3" city_id="-1"/>
    <event id="-2" title="PHP" event_date="2115-07-20 00:00:00.0" reg_link="http://www.php.com.ua" address="Shulyavska"
           point="POINT(30.445495 50.454605)" contact="php@gmail.com" city_id="-3"/>
    <event id="-1" title="Java" event_date="2115-07-10 00:00:00.0" reg_link="http://www.java.com.ua"
           address="Beresteyska" point="POINT(30.742017 50.458585)" contact="java@gmail.com" city_id="-1"/>
    <technology id="-10" name="SQL"/>
    <technology id="-9" name="MyBatis"/>
    <technology id="-8" name="Spring"/>
    <technology id="-7" name="Ant"/>
    <technology id="-6" name="Maven"/>
    <technology id="-5" name="Gradle"/>
    <technology id="-4" name="Liquibase"/>
    <technology id="-3" name="PHP"/>
    <technology id="-2" name="JavaScript"/>
    <technology id="-1" name="Java"/>
    <event_technology event_id="-7" technology_id="-7"/>
    <event_technology event_id="-6" technology_id="-6"/>
    <event_technology event_id="-5" technology_id="-5"/>
    <event_technology event_id="-4" technology_id="-3"/>
    <event_technology event_id="-4" technology_id="-1"/>
    <event_technology event_id="-3" technology_id="-3"/>
    <event_technology event_id="-2" technology_id="-2"/>
    <event_technology event_id="-1" technology_id="-9"/>
    <event_technology event_id="-1" technology_id="-8"/>
    <event_technology event_id="-1" technology_id="-4"/>
    <event_technology event_id="-1" technology_id="-1"/>
</dataset>

=== JujaLabs/itevents/restservice/src/test/resources/dbunit/empty.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--<!DOCTYPE dataset SYSTEM "src/test/resources/dbunit/test.dtd">-->
<dataset>
    <city/>
    <currency/>
    <event/>
    <role/>
    <user_profile/>
    <visit_log/>
    <technology/>
    <event_technology/>
    <filter/>
    <filter_technology/>
    <user_filter/>
</dataset>
